/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9/MdniNtnJkA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9/MdniNtnJkA= >>
// ----------- >>
public class Aereo {
    // ----------- << attribute.annotations@AAAAAAF9/MgRStuRhzk= >>
    // ----------- >>
    private int codice;

    // ----------- << attribute.annotations@AAAAAAF+Jxcq5G3ROy0= >>
    // ----------- >>
    private int numBagCabina;

    // ----------- << attribute.annotations@AAAAAAF9/MsGmdyDE2k= >>
    // ----------- >>
    private Set<Volo> appartieneAvolo = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9/PpvGm5Swtk= >>
    // ----------- >>
    private Set<Posto> parteDi = new HashSet<>();

    private int getCodice() {
        return codice;
    }

    private int getNumBagCabina() {
        return numBagCabina;
    }

    public Set<Volo> getAppartieneAvolo() {
        return appartieneAvolo;
    }

    public Set<Posto> getParteDi() {
        return parteDi;
    }

    private void setCodice(int codice) {
        this.codice = codice;
    }

    private void setNumBagCabina(int numBagCabina) {
        this.numBagCabina = numBagCabina;
    }

    public void linkAppartieneAvolo(Volo _appartieneAvolo) {
        if (_appartieneAvolo != null) {
            _appartieneAvolo.unlinkViaggiaSuAereo();
            _appartieneAvolo.setViaggiaSuAereo(this);
            getAppartieneAvolo().add(_appartieneAvolo);
        }
    }

    public void linkParteDi(Posto _parteDi) {
        if (_parteDi != null) {
            _parteDi.unlinkContiene();
            _parteDi.setContiene(this);
            getParteDi().add(_parteDi);
        }
    }

    public void unlinkAppartieneAvolo(Volo _appartieneAvolo) {
        if (_appartieneAvolo != null) {
            _appartieneAvolo.setViaggiaSuAereo(null);
            getAppartieneAvolo().remove(_appartieneAvolo);
        }
    }

    public void unlinkAppartieneAvolo(Volo _appartieneAvolo, Iterator<Volo> it) {
        if (_appartieneAvolo != null) {
            _appartieneAvolo.setViaggiaSuAereo(null);
            it.remove();
        }
    }

    public void unlinkParteDi(Posto _parteDi) {
        if (_parteDi != null) {
            _parteDi.setContiene(null);
            getParteDi().remove(_parteDi);
        }
    }

    public void unlinkParteDi(Posto _parteDi, Iterator<Posto> it) {
        if (_parteDi != null) {
            _parteDi.setContiene(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9/MdniNtnJkA= >>
// ----------- >>
}