/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF+JtnFX/3dlmM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF+JtnFX/3dlmM= >>
// ----------- >>
public class CompagniViaggio {
    // ----------- << attribute.annotations@AAAAAAF+JtpUcv73vi0= >>
    // ----------- >>
    private String codiceFiscaleCliente;

    // ----------- << attribute.annotations@AAAAAAF+JtrKVAAbqII= >>
    // ----------- >>
    private String codiceFiscaleAmico;

    // ----------- << attribute.annotations@AAAAAAF+JtsV3QDWetA= >>
    // ----------- >>
    private String codiceVolo;

    // ----------- << attribute.annotations@AAAAAAF+Jt0zZwYMH4I= >>
    // ----------- >>
    private Set<Prenotazione> prenotatoDaAmico = new HashSet<>();

    private String getCodiceFiscaleCliente() {
        return codiceFiscaleCliente;
    }

    private String getCodiceFiscaleAmico() {
        return codiceFiscaleAmico;
    }

    private String getCodiceVolo() {
        return codiceVolo;
    }

    public Set<Prenotazione> getPrenotatoDaAmico() {
        return prenotatoDaAmico;
    }

    private void setCodiceFiscaleCliente(String codiceFiscaleCliente) {
        this.codiceFiscaleCliente = codiceFiscaleCliente;
    }

    private void setCodiceFiscaleAmico(String codiceFiscaleAmico) {
        this.codiceFiscaleAmico = codiceFiscaleAmico;
    }

    private void setCodiceVolo(String codiceVolo) {
        this.codiceVolo = codiceVolo;
    }

    public void linkPrenotatoDaAmico(Prenotazione _prenotatoDaAmico) {
        if (_prenotatoDaAmico != null) {
    		_prenotatoDaAmico.getPrenotaPerAmici().add(this);
            getPrenotatoDaAmico().add(_prenotatoDaAmico);
        }
    }

    public void unlinkPrenotatoDaAmico(Prenotazione _prenotatoDaAmico) {
        if (_prenotatoDaAmico != null) {
            _prenotatoDaAmico.getPrenotaPerAmici().remove(this);
            getPrenotatoDaAmico().remove(_prenotatoDaAmico);
        }
    };

    public void unlinkPrenotatoDaAmico(Prenotazione _prenotatoDaAmico, Iterator<Prenotazione> it) {
        if (_prenotatoDaAmico != null) {
            _prenotatoDaAmico.getPrenotaPerAmici().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF+JtnFX/3dlmM= >>
// ----------- >>
}