/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9/NClsejMRiY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9/NClsejMRiY= >>
// ----------- >>
public class tente {
    // ----------- << attribute.annotations@AAAAAAF9/NC6gukykLI= >>
    // ----------- >>
    private String email;

    // ----------- << attribute.annotations@AAAAAAF9/NECVemzdxk= >>
    // ----------- >>
    private void password: String;

    private String getEmail() {
        return email;
    }

    private void getPassword: String() {
        return password: String;
    }

    private void setEmail(String email) {
        this.email = email;
    }

    private void setPassword: String(void password: String) {
        this.password: String = password: String;
    }

    // ----------- << method.annotations@AAAAAAF9/NHwbewRO00= >>
    // ----------- >>
    public void getEmail() {
    // ----------- << method.body@AAAAAAF9/NHwbewRO00= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9/NJJkuzI7cs= >>
    // ----------- >>
    public void getPassword() {
    // ----------- << method.body@AAAAAAF9/NJJkuzI7cs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9/NJzpu0XLTU= >>
    // ----------- >>
    public void setPassword() {
    // ----------- << method.body@AAAAAAF9/NJzpu0XLTU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9/NClsejMRiY= >>
// ----------- >>
}