/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.demo.models;

import java.util.*;

public class Operatore {

    private String nome;
    private String cognome;
    private String email;
    private String PSW;

    
    private String getNome() {
        return nome;
    }

    private String getCognome() {
        return cognome;
    }

    private String getEmail() {
        return email;
    }

    private String getPSW() {
        return PSW;
    }

    private void setNome(String nome) {
        this.nome = nome;
    }

    private void setCognome(String cognome) {
        this.cognome = cognome;
    }

    private void setEmail(String email) {
        this.email = email;
    }

    private void setPSW(String PSW) {
        this.PSW = PSW;
    }

    /**
     * L'operatore nel momento in cui decide di inserire un nuovo volo
    * @param codiceAereo 
    * @param aeroporto 
    * @param orario 
    * @param prezzo
    */

    public void inserisciVolo(String codiceAereo, String aeroporto, LocalDateTime orario, double prezzo) {
    
    }
}