/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.demo.models;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9/MiOEtvEQ58= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9/MiOEtvEQ58= >>
// ----------- >>
public class Posto {
    // ----------- << attribute.annotations@AAAAAAF9/MjMbdvu+mg= >>
    // ----------- >>
    private int numero;

    // ----------- << attribute.annotations@AAAAAAF9/NNBoO7FjYU= >>
    // ----------- >>
    private boolean prenotato;

    // ----------- << attribute.annotations@AAAAAAF9/OmvUgwps4I= >>
    // ----------- >>
    private int codiceAereo;

    // ----------- << attribute.annotations@AAAAAAF9/PpvGm5TBII= >>
    // ----------- >>
    private Aereo contiene;

    private int getNumero() {
        return numero;
    }

    private boolean isPrenotato() {
        return prenotato;
    }

    private int getCodiceAereo() {
        return codiceAereo;
    }

    public Aereo getContiene() {
        return contiene;
    }

    private void setNumero(int numero) {
        this.numero = numero;
    }

    private void setPrenotato(boolean prenotato) {
        this.prenotato = prenotato;
    }

    private void setCodiceAereo(int codiceAereo) {
        this.codiceAereo = codiceAereo;
    }

    public void setContiene(Aereo contiene) {
        this.contiene = contiene;
    }

    public void linkContiene(Aereo _contiene) {
        if (_contiene != null) {
            _contiene.getParteDi().add(this);
        }

        unlinkContiene();
        setContiene(_contiene);
    }

    public void unlinkContiene() {
        if (getContiene() != null) {
            getContiene().getParteDi().remove(this);
            setContiene(null);
        }
    }

// ----------- << class.extras@AAAAAAF9/MiOEtvEQ58= >>
// ----------- >>
}