/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.demo.models;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9/OjzUQlp5tc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9/OjzUQlp5tc= >>
// ----------- >>
public class Prenotazione {
    // ----------- << attribute.annotations@AAAAAAF9/OlcCAtFcFY= >>
    // ----------- >>
    private String codiceFiscale;

    // ----------- << attribute.annotations@AAAAAAF9/OlrwAur6xk= >>
    // ----------- >>
    private Posto posto;

    // ----------- << attribute.annotations@AAAAAAF+JttEpgGRjKE= >>
    // ----------- >>
    private String codiceVolo;

    // ----------- << attribute.annotations@AAAAAAF+Jt0zZwYL/B0= >>
    // ----------- >>
    private Set<CompagniViaggio> prenotaPerAmici = new HashSet<>();

    private String getCodiceFiscale() {
        return codiceFiscale;
    }

    private Posto getPosto() {
        return posto;
    }

    private String getCodiceVolo() {
        return codiceVolo;
    }

    public Set<CompagniViaggio> getPrenotaPerAmici() {
        return prenotaPerAmici;
    }

    private void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    private void setPosto(Posto posto) {
        this.posto = posto;
    }

    private void setCodiceVolo(String codiceVolo) {
        this.codiceVolo = codiceVolo;
    }

    public void linkPrenotaPerAmici(CompagniViaggio _prenotaPerAmici) {
        if (_prenotaPerAmici != null) {
    		_prenotaPerAmici.getPrenotatoDaAmico().add(this);
            getPrenotaPerAmici().add(_prenotaPerAmici);
        }
    }

    public void unlinkPrenotaPerAmici(CompagniViaggio _prenotaPerAmici) {
        if (_prenotaPerAmici != null) {
            _prenotaPerAmici.getPrenotatoDaAmico().remove(this);
            getPrenotaPerAmici().remove(_prenotaPerAmici);
        }
    };

    public void unlinkPrenotaPerAmici(CompagniViaggio _prenotaPerAmici, Iterator<CompagniViaggio> it) {
        if (_prenotaPerAmici != null) {
            _prenotaPerAmici.getPrenotatoDaAmico().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9/OjzUQlp5tc= >>
// ----------- >>
}