/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.demo.models;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9/MhsctuYemQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9/MhsctuYemQ= >>
// ----------- >>
public class Volo {
    // ----------- << attribute.annotations@AAAAAAF9/MqaP9wDb5c= >>
    // ----------- >>
    private String codice;

    // ----------- << attribute.annotations@AAAAAAF9/OOTUQKfzAU= >>
    // ----------- >>
    private String aeroporto;

    // ----------- << attribute.annotations@AAAAAAF9/OVwwgehSGA= >>
    // ----------- >>
    private LocalDateTime orario;

    // ----------- << attribute.annotations@AAAAAAF9/Oo3TA3XSSM= >>
    // ----------- >>
    private int codiceAereo;

    // ----------- << attribute.annotations@AAAAAAF+JyI+4nhnVg0= >>
    // ----------- >>
    private double prezzo;

    // ----------- << attribute.annotations@AAAAAAF9/OC4mPNnE8o= >>
    // ----------- >>
    private Set<Cliente> prenotatoDa = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9/MsGmdyCfnA= >>
    // ----------- >>
    private Aereo viaggiaSuAereo;

    // ----------- << attribute.annotations@AAAAAAF9/OCsePMG9sI= >>
    // ----------- >>
    private Operatore inseritoDa;

    private String getCodice() {
        return codice;
    }

    private String getAeroporto() {
        return aeroporto;
    }

    private LocalDateTime getOrario() {
        return orario;
    }

    private int getCodiceAereo() {
        return codiceAereo;
    }

    private double getPrezzo() {
        return prezzo;
    }

    public Set<Cliente> getPrenotatoDa() {
        return prenotatoDa;
    }

    public Aereo getViaggiaSuAereo() {
        return viaggiaSuAereo;
    }

    public Operatore getInseritoDa() {
        return inseritoDa;
    }

    private void setAeroporto(String aeroporto) {
        this.aeroporto = aeroporto;
    }

    private void setOrario(LocalDateTime orario) {
        this.orario = orario;
    }

    private void setCodiceAereo(int codiceAereo) {
        this.codiceAereo = codiceAereo;
    }

    private void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

    public void setViaggiaSuAereo(Aereo viaggiaSuAereo) {
        this.viaggiaSuAereo = viaggiaSuAereo;
    }

    public void setInseritoDa(Operatore inseritoDa) {
        this.inseritoDa = inseritoDa;
    }

    public void linkPrenotatoDa(Cliente _prenotatoDa) {
        if (_prenotatoDa != null) {
    		_prenotatoDa.getPrenota().add(this);
            getPrenotatoDa().add(_prenotatoDa);
        }
    }

    public void linkViaggiaSuAereo(Aereo _viaggiaSuAereo) {
        if (_viaggiaSuAereo != null) {
            _viaggiaSuAereo.getAppartieneAvolo().add(this);
        }

        unlinkViaggiaSuAereo();
        setViaggiaSuAereo(_viaggiaSuAereo);
    }

    public void linkInseritoDa(Operatore _inseritoDa) {
        if (_inseritoDa != null) {
            _inseritoDa.getInserisceVolo().add(this);
        }

        unlinkInseritoDa();
        setInseritoDa(_inseritoDa);
    }

    public void unlinkPrenotatoDa(Cliente _prenotatoDa) {
        if (_prenotatoDa != null) {
            _prenotatoDa.getPrenota().remove(this);
            getPrenotatoDa().remove(_prenotatoDa);
        }
    };

    public void unlinkPrenotatoDa(Cliente _prenotatoDa, Iterator<Cliente> it) {
        if (_prenotatoDa != null) {
            _prenotatoDa.getPrenota().remove(this);
            it.remove();
        }
    }

    public void unlinkViaggiaSuAereo() {
        if (getViaggiaSuAereo() != null) {
            getViaggiaSuAereo().getAppartieneAvolo().remove(this);
            setViaggiaSuAereo(null);
        }
    }

    public void unlinkInseritoDa() {
        if (getInseritoDa() != null) {
            getInseritoDa().getInserisceVolo().remove(this);
            setInseritoDa(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF+JxeQJG7JyKo= >>
    // ----------- >>
    public int getPostiSedereDisp() {
    // ----------- << method.body@AAAAAAF+JxeQJG7JyKo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF+Jx5TP3Qbnik= >>
    // ----------- >>
    public int getNumBagCabinaDisp() {
    // ----------- << method.body@AAAAAAF+Jx5TP3Qbnik= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9/MhsctuYemQ= >>
// ----------- >>
}